### ISSUE TITLE
npm audit High            Cross-Site Scripting 

### ISSUE THREAD

**Issue by activedecay** [Leafgard/csv2html#13]
High            Cross-Site Scripting                                          
                                                                                
  Package         mustache                                                      
                                                                                
  Patched in      >=2.2.1                                                       
                                                                                
  Dependency of   csv2html                                                      
                                                                                
  Path            csv2html > data-table > mustache                              
                                                                                
  More info       https://npmjs.com/advisories/62

**Comment by Leafgard** [comment]
Should be fixed.
